package com.alexvas.rtsp.codec

import java.util.concurrent.ArrayBlockingQueue
import java.util.concurrent.TimeUnit

enum class VideoCodecType {
    H264, H265, UNKNOWN
}

enum class AudioCodecType {
    AAC_LC, G711_ALAW, G711_MLAW, UNKNOWN
}

class VideoFrameQueue(frameQueueCapacity: Int): FrameQueue<FrameQueue.VideoFrame>(frameQueueCapacity)
class AudioFrameQueue(frameQueueCapacity: Int): FrameQueue<FrameQueue.AudioFrame>(frameQueueCapacity)

/**
 * Queue for concurrent adding/removing audio/video frames.
 */
open class FrameQueue<T>(private val frameQueueCapacity: Int) {

    interface Frame {
        val data: ByteArray
        val offset: Int
        val length: Int
        val timestampUs: Long  // presentation time in usec
    }

    data class VideoFrame(
        /** Only H264 codec supported */
        val codecType: VideoCodecType,
        /** Indicates whether it is a keyframe or not */
        val isKeyframe: Boolean,
        override val data: ByteArray,
        override val offset: Int,
        override val length: Int,
        /** Video frame timestamp (usec) generated by camera */
        override val timestampUs: Long,
        /** Captured (received) video frame timestamp (msec). If -1, not supported. */
        val capturedTimestampMs: Long = -1
    ) : Frame

    data class AudioFrame(
        val codecType: AudioCodecType,
//      val sampleRate: Int,
        override val data: ByteArray,
        override val offset: Int,
        override val length: Int,
        override val timestampUs: Long,
    ) : Frame

    private val queue = ArrayBlockingQueue<T>(frameQueueCapacity)

    val size: Int
        get() = queue.size

    val capacity: Int
        get() = frameQueueCapacity

    @Throws(InterruptedException::class)
    fun push(frame: T): Boolean {
        if (queue.offer(frame)) {
            return true
        }

        // Queue is full.
        // If the new frame is NOT a keyframe, drop it to avoid accumulation.
        if (frame is VideoFrame && !frame.isKeyframe) {
            return false
        }

        // If it's a keyframe (or audio), try to make room by dropping the oldest frame.
        // This maintains low latency for live streams.
        queue.poll()
        return queue.offer(frame)
    }

    @Throws(InterruptedException::class)
    open fun pop(timeout: Long = 1000): T? {
        try {
            val frame: T? = queue.poll(timeout, TimeUnit.MILLISECONDS)
//            if (frame == null) {
//                Log.w(TAG, "Cannot get frame within 1 sec, queue is empty")
//            }
            return frame
        } catch (e: InterruptedException) {
            Thread.currentThread().interrupt()
        }
        return null
    }

    fun clear() {
        queue.clear()
    }

    fun copyInto(dstFrameQueue: FrameQueue<T>) {
        dstFrameQueue.queue.addAll(queue)
    }

    companion object {
        private val TAG: String = FrameQueue::class.java.simpleName
    }

}
